name: tag

on:
  push:
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Install Go
      uses: actions/setup-go@v3
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0
      id: tagging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        DEFAULT_BUMP: minor

